steps:
  #- name: 'gcr.io/cloud-builders/gsutil'
  #  args: ['mb', 'gs://analytics-weather-data-storage-dev']
#
  #- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #  args:
  #    [
  #      'gcloud', 'storage', 'buckets', 'update',
  #      'gs://analytics-weather-data-storage-dev',
  #      '--update-labels=env=dev,team=analytics,project=analytics-weather-data'
  #    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'analytics-weather-data-forecast-api-extractor-dev'
      - '--runtime=python312'
      - '--trigger-http'
      - '--entry-point=entrypoint'
      - '--region=us-west1'
      - '--source=meteorology/src/crf/api_to_gcs'

timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
