steps:
  # Terraform Init
  - name: hashicorp/terraform:1.8.4
    entrypoint: sh
    args:
      - -c
      - |
        echo "Initializing Terraform with workspace '${_ENV}'"
        terraform init \
          -backend-config="bucket=de-analytics-meteo-${_ENV}-tfstate" \
          -backend-config="prefix=terraform/${_ENV}/open-meteo-api"
    dir: projects/meteo/infrastructure/open-meteo-api

  ## Terraform Workspace Select or Create
  - name: hashicorp/terraform:1.8.4
    entrypoint: sh
    args:
      - -c
      - |
        terraform workspace select ${_ENV} || terraform workspace new ${_ENV}
    dir: projects/meteo/infrastructure/open-meteo-api

  ## Terraform Plan
  - name: hashicorp/terraform:1.8.4
    id: plan
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan -var-file="${_ENV}.tfvars"
    dir: projects/meteo/infrastructure/open-meteo-api

  # Terraform Apply
  - name: hashicorp/terraform:1.8.4
    entrypoint: sh
    args:
      - -c
      - |
        terraform apply -auto-approve -var-file="${_ENV}.tfvars"
    dir: projects/meteo/infrastructure/open-meteo-api

  ### Terraform Destroy
  #- name: hashicorp/terraform:1.8.4
  #  entrypoint: sh
  #  args:
  #    - -c
  #    - |
  #      terraform destroy -auto-approve -var-file="${_ENV}.tfvars"
  #  dir: projects/meteo/infrastructure/open-meteo-api

timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY